@base_url = http://127.0.0.1:5000


###
# api/v1/auth/login
# @name login
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "email": "asj214@naver.com",
    "password": "1234"
}

@access_token = {{login.response.body.access_token}}


###
# api/auth/me
GET {{base_url}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# api/posts/index
GET {{base_url}}/api/posts/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "page": 1,
    "per_page": 15
}


###
# api/posts/create
POST {{base_url}}/api/posts/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "hello world",
    "body": "flask/orator/"
}


###
# api/posts/show
GET {{base_url}}/api/posts/4
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# api/posts/update
PUT {{base_url}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "my father goes to the market with donkey",
    "body": "hoo"
}


###
# api/posts/remove
DELETE {{base_url}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# api/posts/update
POST {{base_url}}/api/posts/3/comments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "body": "일요일에 공부"
}


###
# api/posts/delete
DELETE {{base_url}}/api/posts/2/comments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "commentable_id": 3
}